### PR TITLE
Make cooldown time response more easily understandable.

### PR DESCRIPTION
**Pull request by CoolCat467**
`You are on cooldown. Try again in 86396.01s` is not very understandable for humans. Humans don't like large quantities of time represented by only seconds. It would be much better if it said the value it means, `You are on cooldown. Try again in 23 hours, 59 minutes, and 56 seconds.` That is precisely what this pull request is for. Now, I've probably messed it up a bit, so please do test this properly before merging, but this would be a great improvement.

### CODE REVIEW

**Comment by CoolCat467** [comment]
Now, there is one very slight bug with the new `printTime` function, if you give it a negative number it sort of freaks out does -1 of the highest represent-able number, and then all 9s for everything else afterword until the response does indeed return the negative time requested. However, I never foresee this occurring in regular functioning unless it ends up being used for other systems as well.

**Review by Linerly — APPROVED** [review]
Thanks for the PR!

**Comment by Linerly** [comment]
I tried testing it, but the `You are on cooldown. Try again in xxxxx.xxs` message still appears…

Apparently `error.startswith('You are on cooldown. Try again in')` throws this error:
`AttributeError: 'CommandOnCooldown' object has no attribute 'startswith'`

**Comment by CoolCat467** [comment]
Oh, use `str(error).startswith('You are on cooldown. Try again in')`

**Comment by Linerly** [comment]
It works, but then I got another error:
```
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 521, in on_command_error
    secs = time[:-1]
TypeError: 'module' object is not subscriptable
```

**Comment by CoolCat467** [comment]
ah, time module imported

**Comment by CoolCat467** [comment]
rename variable `time` to something else, like `seconds` or something

**Comment by CoolCat467** [comment]
wait a minute, totally, wrong, it should be `secs = secs[:-1]`

**Comment by Linerly** [comment]
Yep, now it works:
```
You are on cooldown. Try again in 23 hours, 59 minutes, and 58 seconds.
```

**Pull request merged**
